"""Exact source-column names from SAP_notintime_.xlsx."""

SNAPSHOT_SHEET = "Wartungsplan- Snapshot"
ORDER_SHEET = "Abfrage1"

SNAPSHOT_COLUMNS = {
    "snapshot_date": "Snapshot-Datum (aktueller Datenstand)",
    "maintenance_plan": "Wartungsplan (MPLA.WARPL)",
    "maintenance_item": "Wartungsposition (MPOS.WAPOS)",
    "work_center": "Verantwortlicher Arbeitsplatz (CRHD.ARBPL)",
    "work_center_object_id": "Arbeitsplatz Objekt-ID (MPOS.GEWRK)",
    "technical_location": "Technischer Platz (ILOA.TPLNR)",
    "technical_location_text": "Bezeichnung technischer Platz (IFLOTX.PLTXT)",
    "equipment": "Equipment (MPOS.EQUNR)",
    "equipment_text": "Equipment-Kurztext (EQKT.EQKTX)",
    "item_text": "Kurztext Wartungsposition (MPOS.PSTXT)",
    "task_list_type": "Plangruppentyp (MPOS.PLNTY)",
    "task_list_group": "Plangruppe (MPOS.PLNNR)",
    "task_list_counter": "Plangruppenzähler (MPOS.PLNAL)",
    "strategy": "Aktuelle Wartungsstrategie (MPLA.STRAT)",
    "opening_horizon_percent": "Aktueller Eröffnungshorizont Prozent (MPLA.HORIZ)",
    "opening_horizon_days": "Aktueller Eröffnungshorizont Tage (MPLA.HORIZ_DAYS)",
    "opening_horizon_qualifier": "Eröffnungshorizont Kennzeichen (MPLA.HORIZ_QUALIFIER)",
    "cycle_start": "Aktuelles Startdatum Wartungsplan (MPLA.STADT)",
}

ORDER_COLUMNS = {
    "call_number": "Abrufnummer (MHIO.ABNUM)",
    "maintenance_plan": "Wartungsplan (MHIO.WARPL)",
    "order_number": "Auftrag (AUFK.AUFNR)",
    "call_date": "Abrufdatum (MHIS.ABRUD)",
    "planned_date": "Plandatum (MHIS.NPLDA)",
    "cycle_days": "Wartungszyklus in Tagen (SAP MMPT/T351P, berechnet)",
    "basic_start": "Eckstart (AFKO.GSTRP)",
    "basic_end": "Eckende (AFKO.GLTRP)",
    "technical_completion": "IDAT2 (AUFK.IDAT2)",
    "final_close": "IDAT3 (AUFK.IDAT3)",
    "completion_date": "Abschlussdatum (AUFK.IDAT2/IDAT3)",
    "technical_location": "Technischer Platz (ILOA.TPLNR)",
    "order_text": "Kurztext (AUFK.KTEXT)",
    "work_center": "Verantwortlicher Arbeitsplatz (AUFK.VAPLZ)",
    "technical_location_text": "Bezeichnung technischer Platz (IFLOTX.PLTXT)",
    "confirmed_finish": "GETRI (AFKO.GETRI)",
    "task_list_group": "Plangruppe (AFKO.PLNNR)",
    "late_shift_percent": "VF verspätete Erledigung Prozent (MPLA.VSPOS)",
    "late_tolerance_percent": "Toleranz (+) Prozent (MPLA.TOPOS)",
    "early_shift_percent": "VF verfrühte Erledigung Prozent (MPLA.VSNEG)",
    "early_tolerance_percent": "Toleranz (-) Prozent (MPLA.TONEG)",
    "stretch_factor": "Streckungsfaktor (MPLA.SFAKT)",
    "factory_calendar": "Fabrikkalender (MPLA.FABKL)",
    "opening_horizon_percent": "Eröffnungshorizont Prozent (MPLA.HORIZ)",
    "opening_horizon_days": "Eröffnungshorizont Tage (MPLA.HORIZ_DAYS)",
    "opening_horizon_qualifier": "Eröffnungshorizont Kennzeichen (MPLA.HORIZ_QUALIFIER)",
    "call_interval": "Abrufintervall (MPLA.ABRHO)",
    "call_interval_unit": "Einheit Abrufintervall (MPLA.HUNIT)",
    "call_confirm": "Erledigungspflicht Kennzeichen (MPLA.CALL_CONFIRM)",
    "cycle_start": "Zyklusstart (MPLA.STADT)",
    "strategy": "Strategie (MPLA.STRAT)",
}
